language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy"
  - "pypy3"
install:
  - pip install codecov
  - pip install -r requirements_dev.txt
script: make travis
after_success:
  - codecov
